// docs/src/components/StateDiagramView.tsx
import { useEffect, useRef } from 'react';
import { createDiagram, syncDiagram, type DiagramTheme } from 'afsm-diagram';
import { useLang } from './i18n';

export interface StateDiagramViewProps {
  diagram: string[];
  currentState: string;
  theme?: DiagramTheme;
}

export default function StateDiagramView({
  diagram,
  currentState,
  theme = 'docs',
}: StateDiagramViewProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const cyRef = useRef<ReturnType<typeof createDiagram> | null>(null);
  const sourceRef = useRef('');

  const lang = useLang();
  const emptyText = lang.startsWith('zh') ? '运行示例后此处显示状态图' : 'Run an example to see the state diagram';
  const hasDiagram = diagram.length > 0;

  useEffect(() => {
    if (!hasDiagram || !containerRef.current) return;
    const cy = createDiagram(containerRef.current, theme);
    cyRef.current = cy;
    return () => {
      cy.destroy();
      cyRef.current = null;
      sourceRef.current = '';
    };
  }, [hasDiagram, theme]);

  useEffect(() => {
    const cy = cyRef.current;
    if (!cy || !hasDiagram) return;
    syncDiagram(cy, diagram, currentState, sourceRef);
  }, [diagram, currentState, hasDiagram]);

  if (!hasDiagram) {
    return (
      <div className="flex min-h-[180px] items-center justify-center rounded-md border border-afsm-line bg-black/20">
        <div className="font-afsm-mono text-[13px] text-afsm-text-faint">{emptyText}</div>
      </div>
    );
  }

  return <div ref={containerRef} className="h-[460px] w-full rounded-md border border-afsm-line bg-black/20" />;
}

// devtools/src/components/StateDiagramView.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { createDiagram, syncDiagram, type DiagramTheme } from 'afsm-diagram';

const props = defineProps<{
  diagram: string[];
  currentState: string;
  theme?: DiagramTheme;
}>();

const containerRef = ref<HTMLElement>();
const sourceRef = { current: '' };
let cy: ReturnType<typeof createDiagram> | null = null;

onMounted(() => {
  if (!containerRef.value || !props.diagram.length) return;
  cy = createDiagram(containerRef.value, props.theme ?? 'dark');
  syncDiagram(cy, props.diagram, props.currentState, sourceRef);
});

onBeforeUnmount(() => {
  cy?.destroy();
  cy = null;
  sourceRef.current = '';
});

watch(
  () => [props.diagram, props.currentState, props.theme] as const,
  () => {
    if (!containerRef.value) return;
    if (!cy && props.diagram.length) {
      cy = createDiagram(containerRef.value, props.theme ?? 'dark');
      sourceRef.current = '';
    }
    if (!cy) return;
    if (!props.diagram.length) {
      cy.destroy();
      cy = null;
      sourceRef.current = '';
      return;
    }
    syncDiagram(cy, props.diagram, props.currentState, sourceRef);
  },
  { flush: 'post' },
);
</script>

<template>
  <div ref="containerRef" class="diagram" />
</template>

<style scoped>
.diagram {
  width: 420px;
  height: 460px;
  min-width: 320px;
  border: 1px solid rgba(128, 128, 128, 0.35);
  border-radius: 6px;
}
</style>
